[workspace]
resolver = "2"
members = ["sdk", "examples/*"]


[workspace.dependencies]
dioxus-sdk = { path = "./sdk" }
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "b20db13" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "b20db13" }
